# Generated by Django 3.1.13 on 2021-10-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': ('유저',),
                'verbose_name_plural': '유저',
                'db_table': 'person',
            },
        ),
    ]
