# Generated by Django 3.1.13 on 2021-10-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20211010_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', '여'), ('male', '남')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
