# Generated by Django 3.1.13 on 2021-10-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20211003_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('female', '여'), ('male', '남')], max_length=20, null=True),
        ),
    ]
