# Generated by Django 3.1.13 on 2021-09-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('open_movie', models.DateTimeField()),
                ('director', models.CharField(max_length=300)),
                ('actor', models.CharField(max_length=700)),
                ('genre', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
    ]
