# Generated by Django 3.1.13 on 2021-10-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('open_movie', models.DateTimeField(null=True)),
                ('director', models.CharField(max_length=300)),
                ('actor', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('runningtime', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('img', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
