# Generated by Django 3.1.13 on 2021-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='open_movie',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
