# Generated by Django 3.1.13 on 2021-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210921_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='open_movie',
            field=models.DateTimeField(null=True),
        ),
    ]
