# Generated by Django 3.1.13 on 2021-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210921_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runningtime',
            field=models.CharField(default=14, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
