# Generated by Django 3.1.13 on 2021-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211002_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
